import { AnimatePresence, motion } from 'framer-motion';
import { Download, Github, Menu, Moon, Sun, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { profile } from '../data/profile';
const links=[['About','about'],['Projects','projects'],['Capabilities','capabilities'],['Experience','experience'],['Contact','contact']] as const;
export default function Navbar(){
 const [open,setOpen]=useState(false);const [dark,setDark]=useState(()=>document.documentElement.classList.contains('dark'));const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{document.body.style.overflow=open?'hidden':'';if(open)panel.current?.querySelector<HTMLElement>('button,a')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'&&panel.current){const f=[...panel.current.querySelectorAll<HTMLElement>('button,a')];if(!f.length)return;if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f[f.length-1].focus()}else if(!e.shiftKey&&document.activeElement===f[f.length-1]){e.preventDefault();f[0].focus()}}};addEventListener('keydown',key);return()=>{document.body.style.overflow='';removeEventListener('keydown',key)}},[open]);
 const go=(id:string)=>{setOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 return <><header className="ai-nav"><nav><button className="ai-brand" onClick={()=>go('home')}><span>KK</span><b>Kaung Khant Ko</b></button><div className="ai-nav-links">{links.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}</div><div className="ai-nav-actions"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github/></a><button onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button><a className="nav-resume" href={profile.cvUrl} download><Download/> Resume</a><button className="nav-menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button></div></nav></header><AnimatePresence>{open&&<motion.div ref={panel} className="ai-mobile-menu" role="dialog" aria-modal="true" aria-label="Navigation" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button className="close-menu" onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button>{links.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}<a href={profile.cvUrl} download>Download résumé</a></motion.div>}</AnimatePresence></>;
}
