/**
 * Su Yet Designs — poster collection shown at /design/su-yet-designs.
 *
 * Regenerated by scripts/sync-su-yet.mjs from Figma file Rq9iC81fj5ho5T2vBNt9oV.
 * This committed copy is the fallback used for local dev and whenever the sync
 * cannot run. Wall-label notes live in scripts/su-yet-notes.json (keyed by slug).
 *
 * To add a poster: create a 1080×1080 frame in Figma named `SUYET — <Title>`
 * (an optional ` / <Series>` segment sets the series label).
 */
export type SuYetPiece = {
  no: string;
  title: string;
  series: string;
  year: string;
  medium: string;
  src: string;
  note: string;
};

export const suYetSyncedAt: string | null = null;

export const suYetPieces: SuYetPiece[] = [
  {"no":"01","title":"Open Source","series":"Tech Explained","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/open-source.webp","note":"Freedom over price: the right to study, modify, and share. A CRT-headed figure carries the code while a rusted padlock hangs open above it."},
  {"no":"02","title":"Incognito ≠ Anonymous","series":"Privacy Myths","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/incognito-anonymous.webp","note":"Private is not anonymous. A classical bust in dark glasses and a fedora, watched by a red targeting reticle, asks what the browser actually hides."},
  {"no":"03","title":"Networking → Collaboration","series":"Community Notes","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/networking-collaboration.webp","note":"Contact turning into collaboration: many hands assembling one red arch from separate blocks — idea to project to opportunity."},
  {"no":"04","title":"Start Small","series":"Start Building","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/start-small.webp","note":"You do not need a huge idea. A single lightbulb rises on a staircase out of crumpled paper — small problems, real projects."},
  {"no":"05","title":"UI ≠ UX","series":"Design Notes","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/ui-ux.webp","note":"Pretty is not enough. A polished phone opens onto a concrete maze with one clear red path — what you see versus how it works."},
  {"no":"06","title":"BUG","series":"Tech Archives","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/bug.webp","note":"The word predates the moth. A 1947 Harvard Mark II logbook and a pinned specimen — \"first actual case of bug being found\" — reconstructed as editorial collage."},
  {"no":"07","title":"Goal First","series":"Student Pathways","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/goal-first.webp","note":"Pick the goal, then the roadmap. A student with a red backpack reads a paper landscape that folds into a staircase to the flag."},
  {"no":"08","title":"Hype ≠ Fit","series":"Career Notes","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/hype-fit.webp","note":"A trend is not a plan. A blindfolded classical bust wrapped in red tape asks whether being surrounded by AI hype means you should become an AI engineer — explore, build, reflect, then choose."},
  {"no":"09","title":"Escape Tutorial Hell","series":"Learn By Building","year":"2026","medium":"Digital poster · 1080×1080","src":"/su-yet/escape-tutorial-hell.webp","note":"One project beats a hundred tutorials. A student walks out of a broken CRT onto an unspooling printout — the tutorial is the map, building is the journey."},
];
