/**
 * Su Yet Designs — poster collection shown at /design/su-yet-designs.
 *
 * This file is regenerated by `scripts/sync-su-yet.mjs` from the linked Figma file
 * (see FIGMA_FILE_KEY in the deploy workflow). The entries below are the committed
 * fallback used for local development and whenever the sync cannot run.
 *
 * To add a poster: create a 1080×1080 frame in Figma named `SUYET — <Title>`
 * (an optional ` / <Series>` segment sets the series label). It appears on the
 * site automatically after the next scheduled sync + deploy.
 */
export type SuYetPiece = {
  no: string;
  title: string;
  series: string;
  year: string;
  medium: string;
  src: string;
  note: string;
};

export const suYetSyncedAt: string | null = null;

export const suYetPieces: SuYetPiece[] = [
  {
    no: '01',
    title: 'Open Source',
    series: 'Tech Explained',
    year: '2026',
    medium: 'Digital poster · 1080×1080',
    src: '/su-yet/open-source.webp',
    note: 'On freedom over price: study, modify, and share. A CRT-headed figure carries the code while a rusted padlock hangs open above it.',
  },
  {
    no: '02',
    title: 'Incognito Mode',
    series: 'Privacy Myths',
    year: '2026',
    medium: 'Digital poster · 1080×1080',
    src: '/su-yet/incognito-mode.webp',
    note: 'Private is not anonymous. A classical bust in dark glasses and a fedora—watched by a red targeting reticle—asks what the browser actually hides.',
  },
  {
    no: '03',
    title: 'Networking',
    series: 'Community Notes',
    year: '2026',
    medium: 'Digital poster · 1080×1080',
    src: '/su-yet/networking.webp',
    note: 'Connection turning into collaboration: many hands assembling one red arch from separate blocks—idea to project to opportunity.',
  },
];
